version: '3.4'

services:
  app:
    image: node:alpine
    environment:
      NODE_ENV: dev
    ports:
      - "3000:3000"
    command: npm run dev
    depends_on:
      - mysql
    volumes:
      - ./../../:/app
    working_dir: /app
  mysql:
    container_name: mysql_host
    image: mysql:5.6
    environment:
      - MYSQL_DATABASE=graphql_project
      - MYSQL_ROOT_PASSWORD=graph_pass
      - MYSQL_USER=graph
      - MYSQL_PASSWORD=graph!!33@
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    volumes:
      - "./../../data/mysql:/var/lib/mysql"